all:
  children:
    all_servers:
      hosts:
        192.168.5.67:
        192.168.5.133:
        192.168.5.119:
    slurmserver:
      hosts:
        192.168.5.67:
    slurmworker:
      hosts:
        192.168.5.133:
        192.168.5.119:
  vars:
    slurm_wn_cpus: 8
    slurm_server_name: 'c1'
    slurm_server_ip: '192.168.5.67'
    slurm_wn_nodenames: ['c2', 'c3']
    etc_hosts_entries: ['192.168.5.67 c1',
                        '192.168.5.133 c2',
                        '192.168.5.119 c3']
    max_run_time: '23:59:59'

