---

- hosts: all_servers
  become: yes
  roles:
    - name: vm_config

- hosts: slurmserver
  become: yes
  tags: slurm
  roles:
    - name: common
    - name: slurm
      slurm_type_of_node: 'front'

- hosts: slurmworker
  become: yes
  tags: slurm
  roles:
    - name: common
    - name: slurm
      slurm_type_of_node: 'wn'
